//
//  genetics.h
//  DNAViewer
//
//  Created by Pete Jensen on 2/21/13.
//  Copyright (c) 2013 PJensen. All rights reserved.
//

#ifndef DNAViewer_genetics_h
#define DNAViewer_genetics_h

#define T7Promoter "TAATACGACTCACTATAGG"
#define SP6Promoter "ATTTAGGTGACACTATAG"
#define T3Promoter "ATTAACCCTCACTAAAGGG"
#define M13Forward "GTTGTAAAACGACGGCCAGT"
#define M13Reverse "TCACACAGGAAACAGCTATGA"
#define AP4Oligo "CCCCTGTGAGGAACT"
#define U19Oligo "GTTTTCCCAGTCACGACGT"
#define HIS6 "CATCATCACCATCACCAC"
#define FLAGEpitope "GATTACAAGGATGACGACGATAAG"
#define ExpressEpitope "GATCTGTACGACGATGACGATAAG"

#define T   'T'
#define C   'C'
#define G   'G'
#define A   'A'

#define IS_AMINO_ACID(x)   (toupper(x) == 'T' || toupper(x) == 'C' || toupper(x) == 'G' || toupper(x) == 'A')

#define MATCH_PATTERN_MAX_LEN   2048
#define MATCH_PATTERN_NAME_LEN  64

struct GeneticSequenceT {
    char fileName[256];
    char *sequence;
};

typedef struct  {
    char patternName[MATCH_PATTERN_NAME_LEN];
    char matchAcids[MATCH_PATTERN_MAX_LEN];
    int matchAcidLength;
    unsigned int match;
} GeneticPatternT;

void initPatterns(void);
void patternDetectionFirstPass(void);
void initPattern(const char* name, const char* sequence);
void patternDetectionFirstPass();
const u_int8_t isAminoAcid(char value);
const long readGeneticData(void);
void calculateMetrics(void);


/***
CMV Promoter:
TAGTAATCAATTACGGGGTCATTAGTTCATAGCCCATATATGGAGTTCCGCGTTACATAACTTACGGTAAATGGCCCGCC
TGGCTGACCGCCCAACGACCCCCGCCCATTGACGTCAATAATGACGTATGTTCCCATAGTAACGCCAATAGGGACTTTCC
ATTGACGTCAATGGGTGGAGTATTTACGGTAAACTGCCCACTTGGCAGTACATCAAGTGTATCATATGCCAAGTACGCCC
CCTATTGACGTCAATGACGGTAAATGGCCCGCCTGGCATTATGCCCAGTACATGACCTTATGGGACTTTCCTACTTGGCA
GTACATCTACGTATTAGTCATCGCTATTACCATGGTGATGCGGTTTTGGCAGTACATCAATGGGCGTGGATAGCGGTTTG
ACTCACGGGGATTTCCAAGTCTCCACCCCATTGACGTCAATGGGAGTTTGTTTTGGCACCAAAATCAACGGGACTTTCCA
AAATGTCGTAACAACTCCGCCCCATTGACGCAAATGGGCGGTAGGCGTGTACGGTGGGAGGTCTATATAAGCAGAGCTGG
TTTAGTGAACCGTCAG
 
Ampicillin:
atgagtattcaacatttccgtgtcgcccttattcccttttttgcggcattttgccttcctgtttttgctcacccagaaac
gctggtgaaagtaaaagatgctgaagatcagttgggtgcacgagtgggttacatcgaactggatctcaacagcggtaaga
tccttgagagttttcgccccgaagaacgttttccaatgatgagcacttttaaagttctgctatgtggcgcggtattatcc
cgtgttgacgccgggcaagagcaactcggtcgccgcatacactattctcagaatgacttggttgagtactcaccagtcac
agaaaagcatcttacggatggcatgacagtaagagaattatgcagtgctgccataaccatgagtgataacactgcggcca
acttacttctgacaacgatcggaggaccgaaggagctaaccgcttttttgcacaacatgggggatcatgtaactcgcctt
gatcgttgggaaccggagctgaatgaagccataccaaacgacgagcgtgacaccacgatgcctgcagcaatggcaacaac
gttgcgcaaactattaactggcgaactacttactctagcttcccggcaacaattaatagactggatggaggcggataaag
ttgcaggaccacttctgcgctcggcccttccggctggctggtttattgctgataaatctggagccggtgagcgtgggtct
cgcggtatcattgcagcactggggccagatggtaagccctcccgtatcgtagttatctacacgacggggagtcaggcaac
tatggatgaacgaaatagacagatcgctgagataggtgcctcactgattaagcattggtaa
 
Kanamycin:
atgattgaacaagatggattgcacgcaggttctccggccgcttgggtggagaggctattcggctatgactgggcacaaca
gacaatcggctgctctgatgccgccgtgttccggctgtcagcgcaggggcgcccggttctttttgtcaagaccgacctgt
ccggtgccctgaatgaactccaagacgaggcagcgcggctatcgtggctggccacgacgggcgttccttgcgcagctgtg
ctcgacgttgtcactgaagcgggaagggactggctgctattgggcgaagtgccggggcaggatctcctgtcatctcacct
tgctcctgccgagaaagtatccatcatggctgatgcaatgcggcggctgcatacgcttgatccggctacctgcccattcg
accaccaagcgaaacatcgcatcgagcgagcacgtactcggatggaagccggtcttgtcgatcaggatgatctggacgaa
gagcatcaggggctcgcgccagccgaactgttcgccaggctcaaggcgcggatgcccgacggcgaggatctcgtcgtgac
ccatggcgatgcctgcttgccgaatatcatggtggaaaatggccgcttttctggattcatcgactgtggccggctgggtg
tggcggaccgctatcaggacatagcgttggctacccgtgatattgctgaagagcttggcggcgaatgggctgaccgcttc
ctcgtgctttacggtatcgccgctcccgattcgcagcgcatcgccttctatcgccttcttgacgagttcttctga
 
Puromycin:
atgaccgagtacaagcccacggtgcgcctcgccacccgcgacgacgtccccagggccgtacgcaccctcgccgccgcgtt
cgccgactaccccgccacgcgccacaccgtcgatccggaccgccacatcgagcgggtcaccgagctgcaagaactcttcc
tcacgcgcgtcgggctcgacatcggcaaggtgtgggtcgcggacgacggcgccgcggtggcggtctggaccacgccggag
agcgtcgaagcgggggcggtgttcgccgagatcggcccgcgcatggccgagttgagcggttcccggctggccgcgcagca
acagatggaaggcctcctggcgccgcaccggcccaaggagcccgcgtggttcctggccaccgtcggcgtctcgcccgacc
accagggcaagggtctgggcagcgccgtcgtgctccccggagtggaggcggccgagcgcgccggggtgcccgccttcctg
gagacctccgcgccccgcaacctccccttctacgagcggctcggcttcaccgtcaccgccgacgtcgagtgcccgaagga
ccgcgcgacctggtgcatgacccgcaagcccggtgcctga
 
Chlormaphenicol:
atgaactttaataaaattgatttagacaattggaagagaaaagagatatttaatcattatttgaaccaacaaacgacttt
tagtataaccacagaaattgatattagtgttttataccgaaacataaaacaagaaggatataaattttaccctgcattta
ttttcttagtgacaagggtgataaactcaaatacagcttttagaactggttacaatagcgacggagagttaggttattgg
gataagttagagccactttatacaatttttgatggtgtatctaaaacattctctggtatttggactcctgtaaagaatga
cttcaaagagttttatgatttatacctttctgatgtagagaaatataatggttcggggaaattgtttcccaaaacaccta
tacctgaaaatgctttttctctttctattattccatggacttcatttactgggtttaacttaaatatcaataataatagt
aattaccttctacccattattacagcaggaaaattcattaataaaggtaattcaatatatttaccgctatctttacaggt
acatcattctgtttgtgatggttatcatgcaggattgtttatgaactctattcaggaattgtcagataggcctaatgact
ggcttttataa
 
Hygromycin B:
atgaaaaagcctgaactcaccgcgacgtctgtcgagaagtttctgatcgaaaagttcgacagcgtctccgacctgatgca
gctctcggagggcgaagaatctcgtgctttcagcttcgatgtaggagggcgtggatatgtcctgcgggtaaatagctgcg
ccgatggtttctacaaagatcgttatgtttatcggcactttgcatcggccgcgctcccgattccggaagtgcttgacatt
ggggagttcagcgagagcctgacctattgcatctcccgccgtgcacagggtgtcacgttgcaagacctgcctgaaaccga
actgcccgctgttctcgagccggtcgcggaggcgatggatgcgatcgctgcggccgatcttagccagacgagcgggttcg
gcccattcggaccgcaaggaatcggtcaatacactacatggcgtgatttcatatgcgcgattgctgatccccatgtgtat
cactggcaaactgtgatggacgacaccgtcagtgcgtccgtcgcgcaggctctcgatgagctgatgctttgggccgagga
ctgccccgaagtccggcacctcgtgcatgcggatttcggctccaacaatgtcctgacggacaatggccgcataacagcgg
tcattgactggagcgaggcgatgttcggggattcccaatacgaggtcgccaacatcctcttctggaggccgtggttggct
tgtatggagcagcagacgcgctacttcgagcggaggcatccggagcttgcaggatcgccgcgcctccgggcgtatatgct
ccgcattggtcttgaccaactctatcagagcttggttgacggcaatttcgatgatgcagcttgggcgcagggtcgatgcg
acgcaatcgtccgatccggagccgggactgtcgggcgtacacaaatcgcccgcagaagcgcggccgtctggaccgatggc
tgtgtagaagtactcgccgatagtggaaaccgacgccccagcactcgtccgagggcaaaggaatag
 
Zeocin:
atggccaagttgaccagtgccgttccggtgctcaccgcgcgcgacgtcgccggagcggtcgagttctggaccgaccggct
cgggttctcccgggacttcgtggaggacgacttcgccggtgtggtccgggacgacgtgaccctgttcatcagcgcggtcc
aggaccaggtggtgccggacaacaccctggcctgggtgttggtgcgcggcctggacgagctgtacgccgagtggtcggag
gtcgtgtccacgaacttccgggacgcctccgggccggccatgaccgagatcggcgagcagccgtgggggcgggagttcgc
cctgcgcgacccggccggcaactgcgtgcacttcgtggccgaggagcaggactga
 
pUC ORI:
tgagcaaaaggccagcaaaaggccagggaccgtaaaaaggccgcgttgctggcgtttttccataggctccgcccccctga
cgagcatcacaaaaatcgacgctcaagtcagaggtggcgaaacccgacaggactataaagataccaggcgtttccccctg
gaagctccctcgtgcgctctcctgttccgaccctgccgcttaccggatacctgtccgcctttctcccttcgggaagcgtg
gcgctttctcatagctcacgctgtaggtatctcagttcggtgtaggtcgttcgctccaagctgggctgtgtgcacgaacc
ccccgttcagcccgaccgctgcgccttatccggtaactatcgtcttgagtccaacccggtaagacacgacttatcgccac
tggcagcagccactggtaacaggattagcagagcgaggtatgtaggcggtgctacagagttcttgaagtggtggcctaac
tacggctacactagaagaacagtatttggtatctgcgctctgctgaagccagttaccttcggaaaaagagttggtagctc
ttgatccggcaaacaaaccaccgctggtagcggtggtttttttgtttgcaagcagcagattacgcgcagaaaaaaaggat
ctcaagaagatcctttgatcttttctac
 
Neomycin:
atgagccatattcaacgggaaacgtcttgctctaggccgcgattaaattccaacatggatgctgatttatatgggtataa
atgggctcgcgataatgtcgggcaatcaggtgcgacaatctatcgattgtatgggaagcccgatgcgccagagttgtttc
tgaaacatggcaaaggtagcgttgccaatgatgttacagatgagatggtcagactaaactggctgacggaatttatgcct
cttccgaccatcaagcattttatccgtactcctgatgatgcatggttactcaccactgcgatccccgggaaaacagcatt
ccaggtattagaagaatatcctgattcaggtgaaaatattgttgatgcgctggcagtgttcctgcgccggttgcattcga
ttcctgtttgtaattgtccttttaacagcgatcgcgtatttcgtctcgctcaggcgcaatcacgaatgaataacggtttg
gttgatgcgagtgattttgatgacgagcgtaatggctggcctgttgaacaagtctggaaagaaatgcataaacttttgcc
attctcaccggattcagtcgtcactcatggtgatttctcacttgataaccttatttttgacgaggggaaattaataggtt
gtattgatgttggacgagtcggaatcgcagaccgataccaggatcttgccatcctatggaactgcctcggtgagttttct
ccttcattacagaaacggctttttcaaaaatatggtattgataatcctgatatgaataaattgcagtttcatttgatgct
cgatgagtttttctaa
 
BGH polyA:
TGTGCCTTCTAGTTGCCAGCCATCTGTTGTTTGCCCCTCCCCCGTGCCTTCCTTGACCCTGGAAGGTGCCACTCCCACTG
TCCTTTCCTAATAAAATGAGGAAATTGCATCGCATTGTCTGAGTAGGTGTCATTCTATTCTGGGGGGTGGGGTGGGGCAG
GACAGCAAGGGGGAGGATTGGGAAGACAATAGCAGGCATGCTGGGGATGCGGTGGGCTCTATGGC
 
SV40 ORI:
CTGTGGAATGTGTGTCAGTTAGGGTGTGGAAAGTCCCCAGGCTCCCCAGCAGGCAGAAGTATGCAAAGCATGCATCTCAA
TTAGTCAGCAACCAGGTGTGGAAAGTCCCCAGGCTCCCCAGCAGGCAGAAGTATGCAAAGCATGCATCTCAATTAGTCAG
CAACCATAGTCCCGCCCCTAACTCCGCCCATCCCGCCCCTAACTCCGCCCAGTTCCGCCCATTCTCCGCCCCATGGCTGA
CTAATTTTTTTTATTTATGCAGAGGCCGAGGCCGCCTCTGCCTCTGAGCTATTCCAGAAGTAGTGAGGAGGCTTTTTTGG
AGGCCTAGGCTTTTGCAAAAAGCTC
 
SV40 polyAr:
ACTTGTTTATTGCAGCTTATAATGGTTACAAATAAAGCAATAGCATCACAAATTTCACAAATAAAGCATTTTTTTCACTG
CATTCTAGTTGTGGTTTGTCCAAACTCATCAATGTATCTTATCATGTCTGT
 
*/

#endif
